
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Dec 15 18:43:27 CET 2017
//----------------------------------------------------

package compiler.syntax;

import java_cup.runtime.Symbol;
import java.util.*;
import es.uned.lsi.compiler.lexical.*;
import es.uned.lsi.compiler.code.*;
import es.uned.lsi.compiler.intermediate.*;
import es.uned.lsi.compiler.semantic.*;
import es.uned.lsi.compiler.semantic.symbol.*;
import es.uned.lsi.compiler.semantic.type.*;
import es.uned.lsi.compiler.syntax.*;
import compiler.CompilerContext;
import compiler.lexical.*;
import compiler.syntax.nonTerminal.*;
import compiler.semantic.*;
import compiler.semantic.symbol.*;
import compiler.semantic.type.*;
import compiler.intermediate.*;
import compiler.code.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Fri Dec 15 18:43:27 CET 2017
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\154\000\002\002\004\000\002\070\002\000\002\002" +
    "\004\000\002\003\003\000\002\004\006\000\002\005\005" +
    "\000\002\007\004\000\002\007\003\000\002\010\004\000" +
    "\002\010\003\000\002\011\004\000\002\011\003\000\002" +
    "\012\003\000\002\012\003\000\002\054\002\000\002\006" +
    "\004\000\002\006\003\000\002\067\005\000\002\013\004" +
    "\000\002\013\003\000\002\014\007\000\002\014\006\000" +
    "\002\015\003\000\002\015\003\000\002\015\003\000\002" +
    "\016\004\000\002\016\003\000\002\017\014\000\002\020" +
    "\006\000\002\021\003\000\002\021\003\000\002\022\003" +
    "\000\002\022\003\000\002\023\004\000\002\023\003\000" +
    "\002\024\007\000\002\024\006\000\002\024\010\000\002" +
    "\024\005\000\002\025\005\000\002\025\003\000\002\026" +
    "\003\000\002\026\003\000\002\026\003\000\002\027\004" +
    "\000\002\027\003\000\002\030\003\000\002\030\003\000" +
    "\002\031\005\000\002\033\012\000\002\034\003\000\002" +
    "\034\003\000\002\035\005\000\002\035\003\000\002\035" +
    "\003\000\002\036\005\000\002\046\005\000\002\046\003" +
    "\000\002\037\003\000\002\040\003\000\002\041\007\000" +
    "\002\042\004\000\002\042\003\000\002\043\005\000\002" +
    "\032\005\000\002\050\010\000\002\051\003\000\002\052" +
    "\007\000\002\053\003\000\002\063\011\000\002\064\004" +
    "\000\002\064\003\000\002\065\014\000\002\045\006\000" +
    "\002\047\007\000\002\047\006\000\002\047\004\000\002" +
    "\044\005\000\002\044\003\000\002\055\004\000\002\055" +
    "\003\000\002\056\003\000\002\056\003\000\002\056\003" +
    "\000\002\056\003\000\002\056\003\000\002\056\003\000" +
    "\002\056\003\000\002\060\004\000\002\057\007\000\002" +
    "\061\007\000\002\062\006\000\002\062\007\000\002\066" +
    "\005\000\002\066\005\000\002\066\005\000\002\066\004" +
    "\000\002\066\005\000\002\066\005\000\002\066\005\000" +
    "\002\066\005\000\002\066\004\000\002\066\003\000\002" +
    "\066\003\000\002\066\003\000\002\066\003\000\002\066" +
    "\003\000\002\066\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\336\000\004\023\000\001\002\000\004\002\340\001" +
    "\002\000\004\023\007\001\002\000\004\002\uffff\001\002" +
    "\000\004\054\336\001\002\000\004\002\ufffe\001\002\000" +
    "\016\011\ufff3\013\026\027\012\034\022\035\036\054\030" +
    "\001\002\000\004\054\311\001\002\000\016\011\ufff3\013" +
    "\026\027\012\034\022\035\036\054\030\001\002\000\014" +
    "\011\uffe7\027\uffe7\034\uffe7\035\uffe7\054\uffe7\001\002\000" +
    "\006\011\uffd2\027\uffd2\001\002\000\004\052\302\001\002" +
    "\000\012\011\uffdf\027\uffdf\035\uffdf\054\uffdf\001\002\000" +
    "\004\011\ufff4\001\002\000\016\011\ufff3\013\026\027\012" +
    "\034\022\035\036\054\030\001\002\000\004\054\243\001" +
    "\002\000\004\011\ufff6\001\002\000\004\011\ufff8\001\002" +
    "\000\004\011\ufffa\001\002\000\004\054\237\001\002\000" +
    "\016\011\uffee\013\uffee\027\uffee\034\uffee\035\uffee\054\uffee" +
    "\001\002\000\010\043\231\052\uffd9\053\224\001\002\000" +
    "\014\011\ufff3\027\012\034\022\035\036\054\223\001\002" +
    "\000\012\011\ufff3\027\012\035\036\054\223\001\002\000" +
    "\016\011\ufff3\013\026\027\012\034\022\035\036\054\030" +
    "\001\002\000\004\011\051\001\002\000\006\011\ufff5\027" +
    "\012\001\002\000\004\054\041\001\002\000\006\011\uffd3" +
    "\027\uffd3\001\002\000\006\011\uffd4\027\uffd4\001\002\000" +
    "\004\053\042\001\002\000\010\012\046\022\043\054\044" +
    "\001\002\000\016\007\uffd8\011\uffd8\027\uffd8\035\uffd8\051" +
    "\uffd8\054\uffd8\001\002\000\016\007\uffd6\011\uffd6\027\uffd6" +
    "\035\uffd6\051\uffd6\054\uffd6\001\002\000\004\007\047\001" +
    "\002\000\016\007\uffd7\011\uffd7\027\uffd7\035\uffd7\051\uffd7" +
    "\054\uffd7\001\002\000\012\011\uffde\027\uffde\035\uffde\054" +
    "\uffde\001\002\000\006\011\uffd5\027\uffd5\001\002\000\036" +
    "\016\ufff1\017\101\020\105\021\073\022\103\024\066\033" +
    "\072\037\060\040\100\041\064\046\106\050\075\054\102" +
    "\055\076\001\002\000\004\016\053\001\002\000\004\054" +
    "\055\001\002\000\004\002\ufffd\001\002\000\004\007\056" +
    "\001\002\000\004\002\ufff0\001\002\000\036\016\ufff2\017" +
    "\101\020\105\021\073\022\103\024\066\033\072\037\060" +
    "\040\100\041\064\046\106\050\075\054\102\055\076\001" +
    "\002\000\004\050\204\001\002\000\042\015\uffac\016\uffac" +
    "\017\uffac\020\uffac\021\uffac\022\uffac\024\uffac\030\uffac\033" +
    "\uffac\037\uffac\040\uffac\041\uffac\046\uffac\050\uffac\054\uffac" +
    "\055\uffac\001\002\000\016\005\115\006\116\007\203\026" +
    "\117\042\114\043\113\001\002\000\034\005\uff9b\006\uff9b" +
    "\007\uff9b\014\uff9b\026\uff9b\031\uff9b\032\uff9b\042\uff9b\043" +
    "\uff9b\044\uff9b\047\uff9b\051\uff9b\052\uff9b\001\002\000\004" +
    "\007\202\001\002\000\042\015\uffae\016\uffae\017\uffae\020" +
    "\uffae\021\uffae\022\uffae\024\uffae\030\uffae\033\uffae\037\uffae" +
    "\040\uffae\041\uffae\046\uffae\050\uffae\054\uffae\055\uffae\001" +
    "\002\000\022\017\101\022\103\024\066\033\072\046\106" +
    "\050\075\054\110\055\076\001\002\000\042\015\uffb0\016" +
    "\uffb0\017\uffb0\020\uffb0\021\uffb0\022\uffb0\024\uffb0\030\uffb0" +
    "\033\uffb0\037\uffb0\040\uffb0\041\uffb0\046\uffb0\050\uffb0\054" +
    "\uffb0\055\uffb0\001\002\000\042\015\uffb1\016\uffb1\017\uffb1" +
    "\020\uffb1\021\uffb1\022\uffb1\024\uffb1\030\uffb1\033\uffb1\037" +
    "\uffb1\040\uffb1\041\uffb1\046\uffb1\050\uffb1\054\uffb1\055\uffb1" +
    "\001\002\000\042\015\uffaa\016\uffaa\017\uffaa\020\uffaa\021" +
    "\uffaa\022\uffaa\024\uffaa\030\uffaa\033\uffaa\037\uffaa\040\uffaa" +
    "\041\uffaa\046\uffaa\050\uffaa\054\uffaa\055\uffaa\001\002\000" +
    "\034\005\uff99\006\uff99\007\uff99\014\uff99\026\uff99\031\uff99" +
    "\032\uff99\042\uff99\043\uff99\044\uff99\047\uff99\051\uff99\052" +
    "\uff99\001\002\000\022\017\101\022\103\024\066\033\072" +
    "\046\106\050\075\054\110\055\076\001\002\000\042\015" +
    "\uffad\016\uffad\017\uffad\020\uffad\021\uffad\022\uffad\024\uffad" +
    "\030\uffad\033\uffad\037\uffad\040\uffad\041\uffad\046\uffad\050" +
    "\uffad\054\uffad\055\uffad\001\002\000\022\017\101\022\103" +
    "\024\066\033\072\046\106\050\075\054\110\055\076\001" +
    "\002\000\034\005\uff96\006\uff96\007\uff96\014\uff96\026\uff96" +
    "\031\uff96\032\uff96\042\uff96\043\uff96\044\uff96\047\uff96\051" +
    "\uff96\052\uff96\001\002\000\042\015\uffab\016\uffab\017\uffab" +
    "\020\uffab\021\uffab\022\uffab\024\uffab\030\uffab\033\uffab\037" +
    "\uffab\040\uffab\041\uffab\046\uffab\050\uffab\054\uffab\055\uffab" +
    "\001\002\000\004\050\163\001\002\000\034\005\uff98\006" +
    "\uff98\007\uff98\014\uff98\026\uff98\031\uff98\032\uff98\042\uff98" +
    "\043\uff98\044\uff98\047\uff98\051\uff98\052\uff98\001\002\000" +
    "\040\005\uff9a\006\uff9a\007\uff9a\017\101\022\103\024\066" +
    "\026\uff9a\033\072\042\uff9a\043\uff9a\044\150\046\106\050" +
    "\146\054\110\055\076\001\002\000\034\005\uff97\006\uff97" +
    "\007\uff97\014\uff97\026\uff97\031\uff97\032\uff97\042\uff97\043" +
    "\uff97\044\uff97\047\uff97\051\uff97\052\uff97\001\002\000\042" +
    "\015\uffaf\016\uffaf\017\uffaf\020\uffaf\021\uffaf\022\uffaf\024" +
    "\uffaf\030\uffaf\033\uffaf\037\uffaf\040\uffaf\041\uffaf\046\uffaf" +
    "\050\uffaf\054\uffaf\055\uffaf\001\002\000\022\017\101\022" +
    "\103\024\066\033\072\046\106\050\075\054\110\055\076" +
    "\001\002\000\022\017\101\022\103\024\066\033\072\046" +
    "\106\050\075\054\110\055\076\001\002\000\016\005\115" +
    "\006\116\026\117\042\114\043\113\047\133\001\002\000" +
    "\054\005\uff9a\006\uff9a\007\uff9a\014\uff9a\017\101\022\103" +
    "\024\066\026\uff9a\031\uff9a\032\uff9a\033\072\042\uff9a\043" +
    "\uff9a\044\uff9a\046\106\047\uff9a\050\111\051\uff9a\052\uff9a" +
    "\054\110\055\076\001\002\000\022\017\101\022\103\024" +
    "\066\033\072\046\106\050\075\054\110\055\076\001\002" +
    "\000\034\005\115\006\116\007\uff9c\014\uff9c\026\117\031" +
    "\uff9c\032\uff9c\042\114\043\113\044\uff9c\047\uff9c\051\uff9c" +
    "\052\uff9c\001\002\000\022\017\101\022\103\024\066\033" +
    "\072\046\106\050\075\054\110\055\076\001\002\000\022" +
    "\017\101\022\103\024\066\033\072\046\106\050\075\054" +
    "\110\055\076\001\002\000\022\017\101\022\103\024\066" +
    "\033\072\046\106\050\075\054\110\055\076\001\002\000" +
    "\022\017\101\022\103\024\066\033\072\046\106\050\075" +
    "\054\110\055\076\001\002\000\022\017\101\022\103\024" +
    "\066\033\072\046\106\050\075\054\110\055\076\001\002" +
    "\000\034\005\uff9d\006\uff9d\007\uff9d\014\uff9d\026\uff9d\031" +
    "\uff9d\032\uff9d\042\uff9d\043\uff9d\044\uff9d\047\uff9d\051\uff9d" +
    "\052\uff9d\001\002\000\034\005\115\006\uffa3\007\uffa3\014" +
    "\uffa3\026\117\031\uffa3\032\uffa3\042\114\043\113\044\uffa3" +
    "\047\uffa3\051\uffa3\052\uffa3\001\002\000\034\005\uffa4\006" +
    "\uffa4\007\uffa4\014\uffa4\026\117\031\uffa4\032\uffa4\042\114" +
    "\043\113\044\uffa4\047\uffa4\051\uffa4\052\uffa4\001\002\000" +
    "\034\005\uffa0\006\uffa0\007\uffa0\014\uffa0\026\uffa0\031\uffa0" +
    "\032\uffa0\042\uffa0\043\uffa0\044\uffa0\047\uffa0\051\uffa0\052" +
    "\uffa0\001\002\000\034\005\uff9f\006\uff9f\007\uff9f\014\uff9f" +
    "\026\uff9f\031\uff9f\032\uff9f\042\uff9f\043\uff9f\044\uff9f\047" +
    "\uff9f\051\uff9f\052\uff9f\001\002\000\006\051\131\052\130" +
    "\001\002\000\020\005\115\006\116\026\117\042\114\043" +
    "\113\051\127\052\uffb3\001\002\000\034\005\uffa2\006\uffa2" +
    "\007\uffa2\014\uffa2\026\uffa2\031\uffa2\032\uffa2\042\uffa2\043" +
    "\uffa2\044\uffa2\047\uffa2\051\uffa2\052\uffa2\001\002\000\022" +
    "\017\101\022\103\024\066\033\072\046\106\050\075\054" +
    "\110\055\076\001\002\000\034\005\uffb8\006\uffb8\007\uffb8" +
    "\014\uffb8\026\uffb8\031\uffb8\032\uffb8\042\uffb8\043\uffb8\044" +
    "\uffb8\047\uffb8\051\uffb8\052\uffb8\001\002\000\020\005\115" +
    "\006\116\026\117\042\114\043\113\051\uffb4\052\uffb4\001" +
    "\002\000\034\005\uff9e\006\uff9e\007\uff9e\014\uff9e\026\uff9e" +
    "\031\uff9e\032\uff9e\042\uff9e\043\uff9e\044\uff9e\047\uff9e\051" +
    "\uff9e\052\uff9e\001\002\000\016\005\115\006\116\026\117" +
    "\042\114\043\113\044\135\001\002\000\022\017\101\022" +
    "\103\024\066\033\072\046\106\050\075\054\110\055\076" +
    "\001\002\000\016\005\115\006\116\026\117\032\137\042" +
    "\114\043\113\001\002\000\022\017\101\022\103\024\066" +
    "\033\072\046\106\050\075\054\110\055\076\001\002\000" +
    "\016\005\115\006\116\014\141\026\117\042\114\043\113" +
    "\001\002\000\034\017\101\020\105\021\073\022\103\024" +
    "\066\033\072\037\060\040\100\041\064\046\106\050\075" +
    "\054\102\055\076\001\002\000\036\016\143\017\101\020" +
    "\105\021\073\022\103\024\066\033\072\037\060\040\100" +
    "\041\064\046\106\050\075\054\102\055\076\001\002\000" +
    "\004\007\145\001\002\000\042\015\uffb2\016\uffb2\017\uffb2" +
    "\020\uffb2\021\uffb2\022\uffb2\024\uffb2\030\uffb2\033\uffb2\037" +
    "\uffb2\040\uffb2\041\uffb2\046\uffb2\050\uffb2\054\uffb2\055\uffb2" +
    "\001\002\000\042\015\uffb9\016\uffb9\017\uffb9\020\uffb9\021" +
    "\uffb9\022\uffb9\024\uffb9\030\uffb9\033\uffb9\037\uffb9\040\uffb9" +
    "\041\uffb9\046\uffb9\050\uffb9\054\uffb9\055\uffb9\001\002\000" +
    "\024\017\101\022\103\024\066\033\072\046\106\050\075" +
    "\051\157\054\110\055\076\001\002\000\020\005\115\006" +
    "\116\007\uff9c\026\117\042\114\043\113\044\153\001\002" +
    "\000\022\017\101\022\103\024\066\033\072\046\106\050" +
    "\075\054\110\055\076\001\002\000\016\005\115\006\116" +
    "\007\152\026\117\042\114\043\113\001\002\000\042\015" +
    "\uffa6\016\uffa6\017\uffa6\020\uffa6\021\uffa6\022\uffa6\024\uffa6" +
    "\030\uffa6\033\uffa6\037\uffa6\040\uffa6\041\uffa6\046\uffa6\050" +
    "\uffa6\054\uffa6\055\uffa6\001\002\000\022\017\101\022\103" +
    "\024\066\033\072\046\106\050\075\054\110\055\076\001" +
    "\002\000\016\005\115\006\116\007\155\026\117\042\114" +
    "\043\113\001\002\000\042\015\uffa5\016\uffa5\017\uffa5\020" +
    "\uffa5\021\uffa5\022\uffa5\024\uffa5\030\uffa5\033\uffa5\037\uffa5" +
    "\040\uffa5\041\uffa5\046\uffa5\050\uffa5\054\uffa5\055\uffa5\001" +
    "\002\000\006\051\161\052\130\001\002\000\004\007\160" +
    "\001\002\000\042\015\uffb6\016\uffb6\017\uffb6\020\uffb6\021" +
    "\uffb6\022\uffb6\024\uffb6\030\uffb6\033\uffb6\037\uffb6\040\uffb6" +
    "\041\uffb6\046\uffb6\050\uffb6\054\uffb6\055\uffb6\001\002\000" +
    "\016\005\uffb8\006\uffb8\007\uffb8\026\uffb8\042\uffb8\043\uffb8" +
    "\001\002\000\042\015\uffb7\016\uffb7\017\uffb7\020\uffb7\021" +
    "\uffb7\022\uffb7\024\uffb7\030\uffb7\033\uffb7\037\uffb7\040\uffb7" +
    "\041\uffb7\046\uffb7\050\uffb7\054\uffb7\055\uffb7\001\002\000" +
    "\022\017\101\022\103\024\066\033\072\046\106\050\075" +
    "\054\110\055\076\001\002\000\016\005\115\006\116\026" +
    "\117\042\114\043\113\051\165\001\002\000\004\007\166" +
    "\001\002\000\042\015\uffa7\016\uffa7\017\uffa7\020\uffa7\021" +
    "\uffa7\022\uffa7\024\uffa7\030\uffa7\033\uffa7\037\uffa7\040\uffa7" +
    "\041\uffa7\046\uffa7\050\uffa7\054\uffa7\055\uffa7\001\002\000" +
    "\016\005\115\006\116\026\117\042\114\043\113\051\127" +
    "\001\002\000\016\005\115\006\116\026\117\031\171\042" +
    "\114\043\113\001\002\000\034\017\101\020\105\021\073" +
    "\022\103\024\066\033\072\037\060\040\100\041\064\046" +
    "\106\050\075\054\102\055\076\001\002\000\040\015\173" +
    "\016\ufff3\017\101\020\105\021\073\022\103\024\066\033" +
    "\072\037\060\040\100\041\064\046\106\050\075\054\102" +
    "\055\076\001\002\000\034\017\101\020\105\021\073\022" +
    "\103\024\066\033\072\037\060\040\100\041\064\046\106" +
    "\050\075\054\102\055\076\001\002\000\004\016\uffba\001" +
    "\002\000\004\016\176\001\002\000\004\007\177\001\002" +
    "\000\042\015\uffbc\016\uffbc\017\uffbc\020\uffbc\021\uffbc\022" +
    "\uffbc\024\uffbc\030\uffbc\033\uffbc\037\uffbc\040\uffbc\041\uffbc" +
    "\046\uffbc\050\uffbc\054\uffbc\055\uffbc\001\002\000\036\016" +
    "\uffbb\017\101\020\105\021\073\022\103\024\066\033\072" +
    "\037\060\040\100\041\064\046\106\050\075\054\102\055" +
    "\076\001\002\000\034\005\uffa1\006\uffa1\007\uffa1\014\uffa1" +
    "\026\117\031\uffa1\032\uffa1\042\114\043\113\044\uffa1\047" +
    "\uffa1\051\uffa1\052\uffa1\001\002\000\042\015\uffa9\016\uffa9" +
    "\017\uffa9\020\uffa9\021\uffa9\022\uffa9\024\uffa9\030\uffa9\033" +
    "\uffa9\037\uffa9\040\uffa9\041\uffa9\046\uffa9\050\uffa9\054\uffa9" +
    "\055\uffa9\001\002\000\042\015\uffb5\016\uffb5\017\uffb5\020" +
    "\uffb5\021\uffb5\022\uffb5\024\uffb5\030\uffb5\033\uffb5\037\uffb5" +
    "\040\uffb5\041\uffb5\046\uffb5\050\uffb5\054\uffb5\055\uffb5\001" +
    "\002\000\004\056\205\001\002\000\004\051\206\001\002" +
    "\000\004\007\207\001\002\000\042\015\uffa8\016\uffa8\017" +
    "\uffa8\020\uffa8\021\uffa8\022\uffa8\024\uffa8\030\uffa8\033\uffa8" +
    "\037\uffa8\040\uffa8\041\uffa8\046\uffa8\050\uffa8\054\uffa8\055" +
    "\uffa8\001\002\000\004\011\uffbf\001\002\000\004\011\213" +
    "\001\002\000\006\011\uffc1\027\uffc1\001\002\000\034\017" +
    "\101\020\105\021\073\022\103\024\066\033\072\037\060" +
    "\040\100\041\064\046\106\050\075\054\102\055\076\001" +
    "\002\000\036\016\uffbd\017\101\020\105\021\073\022\103" +
    "\024\066\033\072\037\060\040\100\041\064\046\106\050" +
    "\075\054\102\055\076\001\002\000\004\016\216\001\002" +
    "\000\004\054\217\001\002\000\004\007\220\001\002\000" +
    "\006\011\uffbe\027\uffbe\001\002\000\004\011\ufff7\001\002" +
    "\000\012\011\uffe0\027\uffe0\035\uffe0\054\uffe0\001\002\000" +
    "\006\052\uffd9\053\224\001\002\000\010\012\046\022\043" +
    "\054\044\001\002\000\014\007\226\011\uffdb\027\uffdb\035" +
    "\uffdb\054\uffdb\001\002\000\012\011\uffdd\027\uffdd\035\uffdd" +
    "\054\uffdd\001\002\000\014\011\uffe8\027\uffe8\034\uffe8\035" +
    "\uffe8\054\uffe8\001\002\000\004\011\ufff9\001\002\000\010" +
    "\017\234\033\233\055\235\001\002\000\004\007\236\001" +
    "\002\000\004\007\uffeb\001\002\000\004\007\uffea\001\002" +
    "\000\004\007\uffe9\001\002\000\016\011\uffec\013\uffec\027" +
    "\uffec\034\uffec\035\uffec\054\uffec\001\002\000\004\043\240" +
    "\001\002\000\010\017\234\033\233\055\235\001\002\000" +
    "\004\007\242\001\002\000\016\011\uffed\013\uffed\027\uffed" +
    "\034\uffed\035\uffed\054\uffed\001\002\000\004\043\244\001" +
    "\002\000\004\010\245\001\002\000\004\046\246\001\002" +
    "\000\006\054\250\055\252\001\002\000\004\047\256\001" +
    "\002\000\006\045\uffe3\047\uffe3\001\002\000\004\045\253" +
    "\001\002\000\006\045\uffe4\047\uffe4\001\002\000\004\045" +
    "\254\001\002\000\006\054\250\055\252\001\002\000\004" +
    "\047\uffe5\001\002\000\004\025\257\001\002\000\006\012" +
    "\262\022\260\001\002\000\004\007\uffe2\001\002\000\004" +
    "\007\263\001\002\000\004\007\uffe1\001\002\000\014\011" +
    "\uffe6\027\uffe6\034\uffe6\035\uffe6\054\uffe6\001\002\000\004" +
    "\011\267\001\002\000\004\011\uffc6\001\002\000\006\011" +
    "\uffd1\027\uffd1\001\002\000\036\017\101\020\105\021\073" +
    "\022\103\024\066\030\272\033\072\037\060\040\100\041" +
    "\064\046\106\050\075\054\102\055\076\001\002\000\004" +
    "\016\277\001\002\000\036\017\101\020\105\021\073\022" +
    "\103\024\066\030\272\033\072\037\060\040\100\041\064" +
    "\046\106\050\075\054\102\055\076\001\002\000\022\017" +
    "\101\022\103\024\066\033\072\046\106\050\075\054\110" +
    "\055\076\001\002\000\004\016\uffc3\001\002\000\016\005" +
    "\115\006\116\007\275\026\117\042\114\043\113\001\002" +
    "\000\004\016\uffc2\001\002\000\004\016\uffc4\001\002\000" +
    "\004\054\300\001\002\000\004\007\301\001\002\000\006" +
    "\011\uffc5\027\uffc5\001\002\000\004\054\303\001\002\000" +
    "\006\052\uffda\053\304\001\002\000\010\012\046\022\043" +
    "\054\044\001\002\000\004\007\306\001\002\000\012\011" +
    "\uffdc\027\uffdc\035\uffdc\054\uffdc\001\002\000\004\011\ufffb" +
    "\001\002\000\016\011\uffef\013\uffef\027\uffef\034\uffef\035" +
    "\uffef\054\uffef\001\002\000\004\050\312\001\002\000\010" +
    "\007\ufff3\051\ufff3\054\314\001\002\000\006\007\326\051" +
    "\325\001\002\000\006\052\uffc7\053\uffc7\001\002\000\006" +
    "\052\uffc8\053\uffc8\001\002\000\006\007\uffcc\051\uffcc\001" +
    "\002\000\006\007\uffcb\051\uffcb\001\002\000\006\052\321" +
    "\053\322\001\002\000\004\054\314\001\002\000\010\012" +
    "\046\022\043\054\044\001\002\000\006\007\uffca\051\uffca" +
    "\001\002\000\006\052\uffc9\053\uffc9\001\002\000\006\007" +
    "\331\053\330\001\002\000\004\054\314\001\002\000\006" +
    "\007\uffcd\051\uffcd\001\002\000\006\012\334\022\332\001" +
    "\002\000\016\011\uffc0\013\uffc0\027\uffc0\034\uffc0\035\uffc0" +
    "\054\uffc0\001\002\000\004\007\uffcf\001\002\000\004\007" +
    "\335\001\002\000\004\007\uffce\001\002\000\016\011\uffd0" +
    "\013\uffd0\027\uffd0\034\uffd0\035\uffd0\054\uffd0\001\002\000" +
    "\004\007\337\001\002\000\016\011\ufffc\013\ufffc\027\ufffc" +
    "\034\ufffc\035\ufffc\054\ufffc\001\002\000\004\002\001\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\336\000\006\002\003\070\004\001\001\000\002\001" +
    "\001\000\010\003\005\004\007\005\010\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\046\007" +
    "\033\010\024\011\023\012\022\013\012\014\026\016\030" +
    "\017\013\023\031\024\016\025\015\027\034\030\037\031" +
    "\036\032\014\033\020\050\032\054\017\001\001\000\002" +
    "\001\001\000\042\010\306\011\023\012\022\014\307\016" +
    "\030\017\013\023\031\024\016\025\015\027\034\030\037" +
    "\031\036\032\014\033\020\050\032\054\017\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\050\007\264\010\024\011" +
    "\023\012\022\013\012\014\026\016\030\017\013\023\031" +
    "\024\016\025\015\027\034\030\037\031\036\032\014\033" +
    "\020\040\263\050\032\054\017\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\034" +
    "\011\227\012\022\017\226\023\031\024\016\025\015\027" +
    "\034\030\037\031\036\032\014\033\020\050\032\054\017" +
    "\001\001\000\026\012\220\024\221\025\015\027\034\030" +
    "\037\031\036\032\014\033\020\050\032\054\017\001\001" +
    "\000\050\007\207\010\024\011\023\012\022\013\012\014" +
    "\026\016\030\017\013\023\031\024\016\025\015\027\034" +
    "\030\037\031\036\032\014\033\020\050\032\051\210\054" +
    "\017\001\001\000\004\006\051\001\001\000\014\030\047" +
    "\031\036\032\014\033\020\050\032\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\026\044\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\030\045\062\047\060\055\056\056" +
    "\067\057\103\060\066\061\064\062\073\063\076\065\070" +
    "\066\061\001\001\000\004\067\053\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\026\045\062\047\060\056\143\057\103\060\066\061" +
    "\064\062\073\063\076\065\070\066\061\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\045\062" +
    "\066\200\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\045\062\066\167" +
    "\001\001\000\002\001\001\000\006\045\062\066\166\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\045\062\066\146\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\045\062\066\133" +
    "\001\001\000\006\045\062\066\106\001\001\000\002\001" +
    "\001\000\006\045\062\066\111\001\001\000\010\044\124" +
    "\045\062\066\125\001\001\000\002\001\001\000\006\045" +
    "\062\066\123\001\001\000\006\045\062\066\122\001\001" +
    "\000\006\045\062\066\121\001\001\000\006\045\062\066" +
    "\120\001\001\000\006\045\062\066\117\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\045\062\066\131\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\045\062\066\135\001\001\000\002\001" +
    "\001\000\006\045\062\066\137\001\001\000\002\001\001" +
    "\000\030\045\062\047\060\055\141\056\067\057\103\060" +
    "\066\061\064\062\073\063\076\065\070\066\061\001\001" +
    "\000\026\045\062\047\060\056\143\057\103\060\066\061" +
    "\064\062\073\063\076\065\070\066\061\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\044" +
    "\155\045\062\066\125\001\001\000\002\001\001\000\006" +
    "\045\062\066\150\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\045\062\066\153\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\045\062\066\163\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\030\045\062\047\060\055\171\056\067\057\103\060" +
    "\066\061\064\062\073\063\076\065\070\066\061\001\001" +
    "\000\032\045\062\047\060\054\173\056\143\057\103\060" +
    "\066\061\064\062\073\063\076\064\174\065\070\066\061" +
    "\001\001\000\030\045\062\047\060\055\177\056\067\057" +
    "\103\060\066\061\064\062\073\063\076\065\070\066\061" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\026\045\062\047\060\056\143" +
    "\057\103\060\066\061\064\062\073\063\076\065\070\066" +
    "\061\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\052\211" +
    "\001\001\000\002\001\001\000\032\045\062\047\060\053" +
    "\214\055\213\056\067\057\103\060\066\061\064\062\073" +
    "\063\076\065\070\066\061\001\001\000\026\045\062\047" +
    "\060\056\143\057\103\060\066\061\064\062\073\063\076" +
    "\065\070\066\061\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\026\224\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\015\231\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\015\240\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\020\246\021" +
    "\250\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\021" +
    "\254\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\022\260\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\041\265\001\001" +
    "\000\002\001\001\000\002\001\001\000\034\042\267\043" +
    "\272\045\062\047\060\055\270\056\067\057\103\060\066" +
    "\061\064\062\073\063\076\065\070\066\061\001\001\000" +
    "\002\001\001\000\030\043\275\045\062\047\060\056\143" +
    "\057\103\060\066\061\064\062\073\063\076\065\070\066" +
    "\061\001\001\000\006\045\062\066\273\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\026\304\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\014\035\312\036" +
    "\315\037\314\046\317\054\316\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\037\323\001\001" +
    "\000\004\026\322\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\036\326\037\314\046\317" +
    "\001\001\000\002\001\001\000\004\034\332\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	SyntaxErrorManager syntaxErrorManager = CompilerContext.getSyntaxErrorManager();
	
	public void syntax_error(Symbol symbol)
	{ 
	    Token token = (Token) symbol.value;
	    syntaxErrorManager.syntaxError ("Error sintactico", token);	    
	}
		
	public void unrecovered_syntax_error(java_cup.runtime.Symbol symbol)
	{	
	    Token token = (Token) symbol.value;
	    syntaxErrorManager.syntaxFatalError ("Error fatal", token);
	}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {


	
	SyntaxErrorManager   syntaxErrorManager   = CompilerContext.getSyntaxErrorManager();
	SemanticErrorManager semanticErrorManager = CompilerContext.getSemanticErrorManager ();
	ScopeManagerIF       scopeManager         = CompilerContext.getScopeManager ();
	FinalCodeFactoryIF   finalCodeFactory     = CompilerContext.getFinalCodeFactory ();


  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 107: // expresion ::= ENTERO_TAL_CUAL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",52, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 106: // expresion ::= INTEGER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",52, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 105: // expresion ::= FALSE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",52, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 104: // expresion ::= TRUE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",52, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 103: // expresion ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",52, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 102: // expresion ::= llamadaFuncion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",52, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 101: // expresion ::= IDENTIFICADOR expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",52, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 100: // expresion ::= expresion OR expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",52, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 99: // expresion ::= CORCHETEABIERTO expresion CORCHETECERRADO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",52, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 98: // expresion ::= expresion IGUAL expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",52, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 97: // expresion ::= expresion MAYORQUE expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",52, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 96: // expresion ::= NOT expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",52, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 95: // expresion ::= PARENTESISABIERTO expresion PARENTESISCERRADO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",52, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 94: // expresion ::= expresion PRODUCTO expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",52, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 93: // expresion ::= expresion MINUS expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",52, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 92: // instruccionAsignacion ::= IDENTIFICADOR expresion ASIGNACION expresion PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccionAsignacion",48, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 91: // instruccionAsignacion ::= IDENTIFICADOR ASIGNACION expresion PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccionAsignacion",48, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 90: // instruccionWriteInt ::= WRITEINT PARENTESISABIERTO expresion PARENTESISCERRADO PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccionWriteInt",47, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // instruccionWriteString ::= WRITESTRING PARENTESISABIERTO CADENA PARENTESISCERRADO PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccionWriteString",45, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // instruccionWriteln ::= WRITELN PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccionWriteln",46, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // instruccion ::= instruccionIterativa 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",44, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // instruccion ::= instruccionCondicional 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",44, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // instruccion ::= llamadaProcedimiento 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",44, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // instruccion ::= instruccionAsignacion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",44, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // instruccion ::= instruccionWriteInt 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",44, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // instruccion ::= instruccionWriteString 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",44, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // instruccion ::= instruccionWriteln 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccion",44, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // instrucciones ::= instruccion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instrucciones",43, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // instrucciones ::= instrucciones instruccion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instrucciones",43, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // envioParametros ::= expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("envioParametros",34, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // envioParametros ::= envioParametros COMA expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("envioParametros",34, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // llamadaProcedimiento ::= expresion PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("llamadaProcedimiento",37, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // llamadaProcedimiento ::= IDENTIFICADOR PARENTESISABIERTO PARENTESISCERRADO PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("llamadaProcedimiento",37, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // llamadaProcedimiento ::= IDENTIFICADOR PARENTESISABIERTO envioParametros PARENTESISCERRADO PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("llamadaProcedimiento",37, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // llamadaFuncion ::= IDENTIFICADOR PARENTESISABIERTO envioParametros PARENTESISCERRADO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("llamadaFuncion",35, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // instruccionIterativa ::= FOR expresion ASIGNACION expresion TO expresion DO instrucciones END PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccionIterativa",51, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // else ::= vacio 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("else",50, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // else ::= ELSE instrucciones 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("else",50, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // instruccionCondicional ::= IF expresion THEN instrucciones else END PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccionCondicional",49, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // instruccionesProcedimiento ::= instrucciones 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccionesProcedimiento",41, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // cuerpoProcedimiento ::= BEGIN instruccionesProcedimiento END IDENTIFICADOR PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cuerpoProcedimiento",40, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // declaracionesProcedimiento ::= declaraciones 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionesProcedimiento",39, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // cabeceraProcedimiento ::= PROCEDURE IDENTIFICADOR PARENTESISABIERTO listaParametros PARENTESISCERRADO PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cabeceraProcedimiento",38, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // procedimiento ::= cabeceraProcedimiento declaracionesProcedimiento cuerpoProcedimiento 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("procedimiento",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // instruccionReturn ::= RETURN expresion PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccionReturn",33, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // instruccionesFuncion ::= instruccionReturn 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccionesFuncion",32, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // instruccionesFuncion ::= instrucciones instruccionReturn 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instruccionesFuncion",32, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // cuerpoFuncion ::= BEGIN instruccionesFuncion END IDENTIFICADOR PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cuerpoFuncion",31, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // declaracionesFuncion ::= declaraciones 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionesFuncion",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // parametro ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametro",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // declaracionParametros ::= parametro 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionParametros",36, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // declaracionParametros ::= declaracionParametros COMA parametro 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionParametros",36, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // conjuntoParametros ::= declaracionParametros DOSPUNTOS tiposVariable 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("conjuntoParametros",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // listaParametros ::= vacio 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaParametros",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // listaParametros ::= conjuntoParametros 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaParametros",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // listaParametros ::= listaParametros PUNTOCOMA conjuntoParametros 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaParametros",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // tipoDatoDevuelto ::= BOOLEAN 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoDatoDevuelto",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // tipoDatoDevuelto ::= INTEGER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoDatoDevuelto",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // cabeceraFuncion ::= PROCEDURE IDENTIFICADOR PARENTESISABIERTO listaParametros PARENTESISCERRADO DOSPUNTOS tipoDatoDevuelto PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cabeceraFuncion",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // funcion ::= cabeceraFuncion declaracionesFuncion cuerpoFuncion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("funcion",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // declaracionSubprograma ::= procedimiento 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionSubprograma",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // declaracionSubprograma ::= funcion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionSubprograma",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // declaracionSubprogramas ::= declaracionSubprograma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionSubprogramas",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // declaracionSubprogramas ::= declaracionSubprogramas declaracionSubprograma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionSubprogramas",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // tiposVariable ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tiposVariable",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // tiposVariable ::= BOOLEAN 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tiposVariable",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // tiposVariable ::= INTEGER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tiposVariable",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // listaVariables ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaVariables",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // listaVariables ::= listaVariables COMA IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaVariables",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // declaracionVariable ::= IDENTIFICADOR DOSPUNTOS tiposVariable 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionVariable",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // declaracionVariable ::= listaVariables COMA IDENTIFICADOR DOSPUNTOS tiposVariable PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionVariable",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // declaracionVariable ::= IDENTIFICADOR DOSPUNTOS tiposVariable PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionVariable",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // declaracionVariable ::= VAR IDENTIFICADOR DOSPUNTOS tiposVariable PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionVariable",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // declaracionVariables ::= declaracionVariable 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionVariables",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // declaracionVariables ::= declaracionVariables declaracionVariable 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionVariables",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // tipoDeVector ::= BOOLEAN 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoDeVector",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // tipoDeVector ::= INTEGER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoDeVector",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // tipoIndice ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoIndice",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // tipoIndice ::= ENTERO_TAL_CUAL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoIndice",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // indicesVector ::= tipoIndice PUNTO PUNTO tipoIndice 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("indicesVector",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // vector ::= TYPE IDENTIFICADOR IGUAL ARRAY CORCHETEABIERTO indicesVector CORCHETECERRADO OF tipoDeVector PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("vector",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // declaracionVectores ::= vector 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionVectores",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // declaracionVectores ::= declaracionVectores vector 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionVectores",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // tipoConstante ::= ENTERO_TAL_CUAL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoConstante",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // tipoConstante ::= FALSE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoConstante",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // tipoConstante ::= TRUE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoConstante",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // declaracionConstante ::= IDENTIFICADOR IGUAL tipoConstante PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionConstante",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // declaracionConstante ::= CONST IDENTIFICADOR IGUAL tipoConstante PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionConstante",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // declaracionConstantes ::= declaracionConstante 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionConstantes",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // declaracionConstantes ::= declaracionConstantes declaracionConstante 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionConstantes",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // fin ::= END IDENTIFICADOR PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("fin",53, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // inicio ::= BEGIN 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("inicio",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // inicio ::= BEGIN instrucciones 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("inicio",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // vacio ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("vacio",42, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // declaraciones4 ::= vacio 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaraciones4",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // declaraciones4 ::= declaracionSubprogramas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaraciones4",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // declaraciones3 ::= declaraciones4 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaraciones3",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // declaraciones3 ::= declaracionVariables declaraciones4 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaraciones3",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // declaraciones2 ::= declaraciones3 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaraciones2",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // declaraciones2 ::= declaracionVectores declaraciones3 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaraciones2",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // declaraciones ::= declaraciones2 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaraciones",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // declaraciones ::= declaracionConstantes declaraciones2 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaraciones",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // modulo ::= MODULE IDENTIFICADOR PUNTOCOMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("modulo",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // modulUNED ::= modulo declaraciones inicio fin 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("modulUNED",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // axiom ::= modulUNED 
            {
              Axiom RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // program ::= NT$0 axiom 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int axleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int axright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Axiom ax = (Axiom)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
  		// No modificar esta estructura, aunque se pueden añadir más acciones semánticas
  		// Para la entrega de febrero pueden comentarse las dos sentencias siguientes:
  		//List intermediateCode = ax.getIntermediateCode ();
  		//finalCodeFactory.create (intermediateCode);
  		// En caso de no comentarse las sentencias anteriores puede generar una excepcion
  		// en las llamadas a cupTest en la entrega de Febrero. Esto es debido a que 
  		// aún no se tendrá implementada la generación de código intermedio ni final.
  		// Para la entrega de Junio deberán descomentarse y usarse.
  		
  		syntaxErrorManager.syntaxInfo ("Parsing process ended.");
   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // NT$0 ::= 
            {
              Object RESULT =null;
 
        syntaxErrorManager.syntaxInfo ("Starting parsing..."); 
   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",54, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

