
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Dec 15 18:43:27 CET 2017
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DOSPUNTOS = 41;
  public static final int CONST = 9;
  public static final int INTEGER = 16;
  public static final int PUNTOCOMA = 5;
  public static final int ARRAY = 6;
  public static final int WRITEINT = 30;
  public static final int FOR = 14;
  public static final int MINUS = 3;
  public static final int IDENTIFICADOR = 42;
  public static final int NOT = 18;
  public static final int MAYORQUE = 32;
  public static final int IGUAL = 33;
  public static final int PARENTESISCERRADO = 39;
  public static final int TYPE = 26;
  public static final int OR = 20;
  public static final int BEGIN = 7;
  public static final int PLUS = 2;
  public static final int IF = 15;
  public static final int WRITELN = 31;
  public static final int ENTERO_TAL_CUAL = 43;
  public static final int OF = 19;
  public static final int EOF = 0;
  public static final int BOOLEAN = 8;
  public static final int PRODUCTO = 4;
  public static final int RETURN = 22;
  public static final int TRUE = 25;
  public static final int error = 1;
  public static final int COMA = 40;
  public static final int CADENA = 44;
  public static final int CORCHETECERRADO = 37;
  public static final int ASIGNACION = 34;
  public static final int MODULE = 17;
  public static final int ELSE = 11;
  public static final int PUNTO = 35;
  public static final int WRITESTRING = 29;
  public static final int PARENTESISABIERTO = 38;
  public static final int TO = 24;
  public static final int WHILE = 28;
  public static final int THEN = 23;
  public static final int END = 12;
  public static final int FALSE = 13;
  public static final int CORCHETEABIERTO = 36;
  public static final int VAR = 27;
  public static final int PROCEDURE = 21;
  public static final int DO = 10;
}

